In [1]:
import os

os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

pd.set_option('display.max_rows', 500)

In [4]:
acc = Accountable.objects.get(pk='A6N-13N-62-O1^2015-01-01')
acc

In [9]:
objs_df=pd.DataFrame(Charge.objects.filter(account__in=[13802005], concept__accountable=acc).order_by('concept__date', '-value')\
                     .values('id', 'concept__accountable', 'ledger__third_party', 'ledger_id', 'account_id', 'value', 'concept__date'))
objs_df

,id,concept__accountable,ledger__third_party,ledger_id,account_id,value,concept__date
0,79,A6N-13N-62-O1^2015-01-01,19128434,CA-00000037,13802005,1065000,2022-01-01
1,1106,A6N-13N-62-O1^2015-01-01,19128434,FV-00000037,13802005,1065000,2022-01-01
2,1105,A6N-13N-62-O1^2015-01-01,19128434,FV-00000037,13802005,-1065000,2022-01-01
3,189,A6N-13N-62-O1^2015-01-01,19128434,CA-00000092,13802005,1065000,2022-02-01
4,1228,A6N-13N-62-O1^2015-01-01,19128434,FV-00000092,13802005,1065000,2022-02-01
5,1227,A6N-13N-62-O1^2015-01-01,19128434,FV-00000092,13802005,-1065000,2022-02-01
6,223,A6N-13N-62-O1^2015-01-01,19128434,CA-00000109,13802005,1065000,2022-03-01
7,1268,A6N-13N-62-O1^2015-01-01,19128434,FV-00000109,13802005,1065000,2022-03-01
8,1267,A6N-13N-62-O1^2015-01-01,19128434,FV-00000109,13802005,-1065000,2022-03-01
9,395,A6N-13N-62-O1^2015-01-01,19128434,CA-00000195,13802005,1065000,2022-04-01
10,1464,A6N-13N-62-O1^2015-01-01,19128434,FV-00000195,13802005,1065000,2022-04-01
11,1463,A6N-13N-62-O1^2015-01-01,19128434,FV-00000195,13802005,-1065000,2022-04-01
12,425,A6N-13N-62-O1^2015-01-01,19128434,CA-00000210,13802005,1065000,2022-05-01
13,1500,A6N-13N-62-O1^2015-01-01,19128434,FV-00000210,13802005,1065000,2022-05-01
14,1499,A6N-13N-62-O1^2015-01-01,19128434,FV-00000210,13802005,-1065000,2022-05-01
15,587,A6N-13N-62-O1^2015-01-01,19128434,CA-00000291,13802005,1065000,2022-06-01
16,1684,A6N-13N-62-O1^2015-01-01,19128434,FV-00000291,13802005,1065000,2022-06-01
17,1683,A6N-13N-62-O1^2015-01-01,19128434,FV-00000291,13802005,-1065000,2022-06-01
18,669,A6N-13N-62-O1^2015-01-01,19128434,CA-00000332,13802005,1065000,2022-07-01
19,1778,A6N-13N-62-O1^2015-01-01,19128434,FV-00000332,13802005,1065000,2022-07-01
20,1777,A6N-13N-62-O1^2015-01-01,19128434,FV-00000332,13802005,-1065000,2022-07-01
21,783,A6N-13N-62-O1^2015-01-01,19128434,CA-00000389,13802005,1065000,2022-08-01
22,1906,A6N-13N-62-O1^2015-01-01,19128434,FV-00000389,13802005,1065000,2022-08-01
23,1905,A6N-13N-62-O1^2015-01-01,19128434,FV-00000389,13802005,-1065000,2022-08-01
24,857,A6N-13N-62-O1^2015-01-01,19128434,CA-00000426,13802005,1065000,2022-09-01
25,1990,A6N-13N-62-O1^2015-01-01,19128434,FV-00000426,13802005,1065000,2022-09-01
26,1989,A6N-13N-62-O1^2015-01-01,19128434,FV-00000426,13802005,-1065000,2022-09-01
27,939,A6N-13N-62-O1^2015-01-01,19128434,CA-00000467,13802005,1065000,2022-10-01
28,2084,A6N-13N-62-O1^2015-01-01,19128434,FV-00000467,13802005,1065000,2022-10-01
29,2083,A6N-13N-62-O1^2015-01-01,19128434,FV-00000467,13802005,-1065000,2022-10-01

In [33]:
def GetChargeDue(charge_id):
    cha=Charge.objects.get(pk=charge_id)
    if cha.ledger.type.abreviation == 'CA':
        if Charge.objects.filter(account=cha.account, concept=cha.concept, ledger__type__abreviation='FV', value=-cha.value).exists():
            return 0
    elif cha.ledger.type.abreviation == 'FV' and cha.value < 0:
        if Charge.objects.filter(account=cha.account, concept=cha.concept, ledger__type__abreviation='CA', value=-cha.value).exists():
            return 0        
    elif cha.ledger.type.abreviation == 'FV' and cha.value > 0:
        receipt = Charge.objects.filter(account=cha.account, concept=cha.concept, ledger__type__abreviation='RC', value__gt=0).aggregate(receipt=Sum('value'))['receipt']
        return cha.value + receipt if receipt else cha.value
    else:
        return 0

In [24]:
def DueAge(_dueDate):
    bufferDate=_dueDate
    months=0
    days=0
    while bufferDate < datetime.date.today():
        if bufferDate + relativedelta(months=1) < datetime.date.today():
            months = months +1
        else:
            days=(datetime.date.today() - bufferDate).days
        bufferDate = bufferDate + relativedelta(months=1)
    return f'{months}, {days}'

In [34]:
due_df=objs_df.assign(
    due_value=objs_df.id.apply(lambda x: GetChargeDue(x)),
    due_age=objs_df.concept__date.apply(lambda x: DueAge(x)))
due_df

,id,concept__accountable,ledger__third_party,ledger_id,account_id,value,concept__date,due_value,due_age
0,79,A6N-13N-62-O1^2015-01-01,19128434,CA-00000037,13802005,1065000,2022-01-01,0,"9, 25"
1,1106,A6N-13N-62-O1^2015-01-01,19128434,FV-00000037,13802005,1065000,2022-01-01,1065000,"9, 25"
2,1105,A6N-13N-62-O1^2015-01-01,19128434,FV-00000037,13802005,-1065000,2022-01-01,0,"9, 25"
3,189,A6N-13N-62-O1^2015-01-01,19128434,CA-00000092,13802005,1065000,2022-02-01,0,"8, 25"
4,1228,A6N-13N-62-O1^2015-01-01,19128434,FV-00000092,13802005,1065000,2022-02-01,1065000,"8, 25"
5,1227,A6N-13N-62-O1^2015-01-01,19128434,FV-00000092,13802005,-1065000,2022-02-01,0,"8, 25"
6,223,A6N-13N-62-O1^2015-01-01,19128434,CA-00000109,13802005,1065000,2022-03-01,0,"7, 25"
7,1268,A6N-13N-62-O1^2015-01-01,19128434,FV-00000109,13802005,1065000,2022-03-01,1065000,"7, 25"
8,1267,A6N-13N-62-O1^2015-01-01,19128434,FV-00000109,13802005,-1065000,2022-03-01,0,"7, 25"
9,395,A6N-13N-62-O1^2015-01-01,19128434,CA-00000195,13802005,1065000,2022-04-01,0,"6, 25"
10,1464,A6N-13N-62-O1^2015-01-01,19128434,FV-00000195,13802005,1065000,2022-04-01,1065000,"6, 25"
11,1463,A6N-13N-62-O1^2015-01-01,19128434,FV-00000195,13802005,-1065000,2022-04-01,0,"6, 25"
12,425,A6N-13N-62-O1^2015-01-01,19128434,CA-00000210,13802005,1065000,2022-05-01,0,"5, 25"
13,1500,A6N-13N-62-O1^2015-01-01,19128434,FV-00000210,13802005,1065000,2022-05-01,1065000,"5, 25"
14,1499,A6N-13N-62-O1^2015-01-01,19128434,FV-00000210,13802005,-1065000,2022-05-01,0,"5, 25"
15,587,A6N-13N-62-O1^2015-01-01,19128434,CA-00000291,13802005,1065000,2022-06-01,0,"4, 25"
16,1684,A6N-13N-62-O1^2015-01-01,19128434,FV-00000291,13802005,1065000,2022-06-01,1065000,"4, 25"
17,1683,A6N-13N-62-O1^2015-01-01,19128434,FV-00000291,13802005,-1065000,2022-06-01,0,"4, 25"
18,669,A6N-13N-62-O1^2015-01-01,19128434,CA-00000332,13802005,1065000,2022-07-01,0,"3, 25"
19,1778,A6N-13N-62-O1^2015-01-01,19128434,FV-00000332,13802005,1065000,2022-07-01,1065000,"3, 25"
20,1777,A6N-13N-62-O1^2015-01-01,19128434,FV-00000332,13802005,-1065000,2022-07-01,0,"3, 25"
21,783,A6N-13N-62-O1^2015-01-01,19128434,CA-00000389,13802005,1065000,2022-08-01,0,"2, 25"
22,1906,A6N-13N-62-O1^2015-01-01,19128434,FV-00000389,13802005,1065000,2022-08-01,1065000,"2, 25"
23,1905,A6N-13N-62-O1^2015-01-01,19128434,FV-00000389,13802005,-1065000,2022-08-01,0,"2, 25"
24,857,A6N-13N-62-O1^2015-01-01,19128434,CA-00000426,13802005,1065000,2022-09-01,0,"1, 25"
25,1990,A6N-13N-62-O1^2015-01-01,19128434,FV-00000426,13802005,1065000,2022-09-01,1065000,"1, 25"
26,1989,A6N-13N-62-O1^2015-01-01,19128434,FV-00000426,13802005,-1065000,2022-09-01,0,"1, 25"
27,939,A6N-13N-62-O1^2015-01-01,19128434,CA-00000467,13802005,1065000,2022-10-01,0,"0, 25"
28,2084,A6N-13N-62-O1^2015-01-01,19128434,FV-00000467,13802005,1065000,2022-10-01,1065000,"0, 25"
29,2083,A6N-13N-62-O1^2015-01-01,19128434,FV-00000467,13802005,-1065000,2022-10-01,0,"0, 25"

In [35]:
due_df[due_df['due_value'] != 0]

,id,concept__accountable,ledger__third_party,ledger_id,account_id,value,concept__date,due_value,due_age
1,1106,A6N-13N-62-O1^2015-01-01,19128434,FV-00000037,13802005,1065000,2022-01-01,1065000,"9, 25"
4,1228,A6N-13N-62-O1^2015-01-01,19128434,FV-00000092,13802005,1065000,2022-02-01,1065000,"8, 25"
7,1268,A6N-13N-62-O1^2015-01-01,19128434,FV-00000109,13802005,1065000,2022-03-01,1065000,"7, 25"
10,1464,A6N-13N-62-O1^2015-01-01,19128434,FV-00000195,13802005,1065000,2022-04-01,1065000,"6, 25"
13,1500,A6N-13N-62-O1^2015-01-01,19128434,FV-00000210,13802005,1065000,2022-05-01,1065000,"5, 25"
16,1684,A6N-13N-62-O1^2015-01-01,19128434,FV-00000291,13802005,1065000,2022-06-01,1065000,"4, 25"
19,1778,A6N-13N-62-O1^2015-01-01,19128434,FV-00000332,13802005,1065000,2022-07-01,1065000,"3, 25"
22,1906,A6N-13N-62-O1^2015-01-01,19128434,FV-00000389,13802005,1065000,2022-08-01,1065000,"2, 25"
25,1990,A6N-13N-62-O1^2015-01-01,19128434,FV-00000426,13802005,1065000,2022-09-01,1065000,"1, 25"
28,2084,A6N-13N-62-O1^2015-01-01,19128434,FV-00000467,13802005,1065000,2022-10-01,1065000,"0, 25"

In [10]:
cha = Charge.objects.get(pk=79)
cha

In [12]:
Charge.objects.filter(concept=cha.concept, ledger__type__abreviation='FV', value=-cha.value).exists()

True

In [27]:
Charge.objects.filter(concept=cha.concept, ledger__type__abreviation='RC', value__gt=0).aggregate(receipt=Sum('value'))['receipt']

{'receipt': None}

In [41]:
receipt=-Charge.objects.filter(account__in=[13802005], value__lt=0, ledger__third_party=per).aggregate(receipt=Sum('value'))['receipt']
receipt

31270000

In [48]:
value_sum_df=objs_df.assign(due=objs_df['value'].cumsum())
due_sum_df = value_sum_df.assign(due=value_sum_df.due.apply(lambda x: 0 if x < receipt else x - receipt))
due_df=due_sum_df.assign(due=due_sum_df.apply(lambda x: x.due if x.due < x.value else x.value, axis=1))
filtered_due_df=due_df[due_df['due'] > 0]
age_due_df=filtered_due_df.assign(age=filtered_due_df.concept_id.apply(lambda x: DueAge(Accountable_Concept.objects.get(pk=x).date)))
age_due_df

,ledger_id,account_id,value,concept_id,due,age
17,FV-00000431,13802005,2720000,Facturacion Arriendo sin IVA^2022-09-01_A6N-13...,20000,"1, 11"
18,FV-00000422,13802005,790000,Facturacion Arriendo sin IVA^2022-10-01_A6N-13...,790000,"0, 11"
19,FV-00000432,13802005,2720000,Facturacion Arriendo sin IVA^2022-10-01_A6N-13...,2720000,"0, 11"

In [8]:
pd.DataFrame(Charge.objects.filter(account__in=[13802005], value__lt=0, ledger__third_party=per).values()).drop(['state_change_user_id', 'state_change_date', 'state'], axis=1)

,id,ledger_id,account_id,value,concept_id,settled
0,1205,RC-00000011,13802005,-800000,Ingreso Arriendo sin IVA^2022-01-18_A6N-13N-68...,False
1,1209,RC-00000012,13802005,-750000,Ingreso Arriendo sin IVA^2022-01-25_A6N-13N-68...,False
2,1213,RC-00000013,13802005,-200000,Ingreso Arriendo sin IVA^2022-01-26_A6N-13N-68...,False
3,1217,RC-00000014,13802005,-850000,Ingreso Arriendo sin IVA^2022-01-28_A6N-13N-68...,False
4,1221,RC-00000015,13802005,-700000,Ingreso Arriendo sin IVA^2022-02-14_A6N-13N-68...,False
5,1225,RC-00000016,13802005,-1500000,Ingreso Arriendo sin IVA^2022-02-22_A6N-13N-68...,False
6,1229,RC-00000017,13802005,-250000,Ingreso Arriendo sin IVA^2022-02-28_A6N-13N-68...,False
7,1233,RC-00000018,13802005,-270000,Ingreso Arriendo sin IVA^2022-03-02_A6N-13N-68...,False
8,1237,RC-00000019,13802005,-2000000,Ingreso Arriendo sin IVA^2022-03-23_A6N-13N-68...,False
9,1241,RC-00000020,13802005,-720000,Ingreso Arriendo sin IVA^2022-03-31_A6N-13N-68...,False
10,1245,RC-00000021,13802005,-2000000,Ingreso Arriendo sin IVA^2022-04-22_A6N-13N-68...,False
11,1249,RC-00000022,13802005,-720000,Ingreso Arriendo sin IVA^2022-05-05_A6N-13N-68...,False
12,1253,RC-00000023,13802005,-1800000,Ingreso Arriendo sin IVA^2022-05-23_A6N-13N-68...,False
13,1257,RC-00000024,13802005,-920000,Ingreso Arriendo sin IVA^2022-06-03_A6N-13N-68...,False
14,1261,RC-00000025,13802005,-1350000,Ingreso Arriendo sin IVA^2022-06-29_A6N-13N-68...,False
15,1265,RC-00000026,13802005,-1370000,Ingreso Arriendo sin IVA^2022-07-08_A6N-13N-68...,False
16,1269,RC-00000027,13802005,-2000000,Ingreso Arriendo sin IVA^2022-07-25_A6N-13N-68...,False
17,1273,RC-00000028,13802005,-720000,Ingreso Arriendo sin IVA^2022-08-03_A6N-13N-68...,False
18,1277,RC-00000029,13802005,-1000000,Ingreso Arriendo sin IVA^2022-08-24_A6N-13N-68...,False
19,1281,RC-00000030,13802005,-1500000,Ingreso Arriendo sin IVA^2022-08-26_A6N-13N-68...,False
20,1285,RC-00000031,13802005,-220000,Ingreso Arriendo sin IVA^2022-08-28_A6N-13N-68...,False
21,1289,RC-00000032,13802005,-1000000,Ingreso Arriendo sin IVA^2022-09-14_A6N-13N-68...,False
22,1293,RC-00000033,13802005,-1000000,Ingreso Arriendo sin IVA^2022-09-20_A6N-13N-68...,False
23,1297,RC-00000034,13802005,-200000,Ingreso Arriendo sin IVA^2022-09-20_A6N-13N-68...,False
24,1301,RC-00000035,13802005,-500000,Ingreso Arriendo sin IVA^2022-09-30_A6N-13N-68...,False
25,1305,RC-00000036,13802005,-730000,Ingreso Arriendo sin IVA^2022-01-14_A6N-13N-66...,False
26,1309,RC-00000037,13802005,-730000,Ingreso Arriendo sin IVA^2022-02-14_A6N-13N-66...,False
27,1313,RC-00000038,13802005,-730000,Ingreso Arriendo sin IVA^2022-03-11_A6N-13N-66...,False
28,1317,RC-00000039,13802005,-790000,Ingreso Arriendo sin IVA^2022-04-19_A6N-13N-66...,False
29,1321,RC-00000040,13802005,-790000,Ingreso Arriendo sin IVA^2022-05-23_A6N-13N-66...,False
30,1325,RC-00000041,13802005,-790000,Ingreso Arriendo sin IVA^2022-06-14_A6N-13N-66...,False
31,1329,RC-00000042,13802005,-790000,Ingreso Arriendo sin IVA^2022-07-15_A6N-13N-66...,False
32,1333,RC-00000043,13802005,-700000,Ingreso Arriendo sin IVA^2022-08-09_A6N-13N-66...,False
33,1337,RC-00000044,13802005,-90000,Ingreso Arriendo sin IVA^2022-08-16_A6N-13N-66...,False
34,1341,RC-00000045,13802005,-790000,Ingreso Arriendo sin IVA^2022-09-14_A6N-13N-66...,False

3530000