In [3]:
import os

os.environ["DJANGO_ALLOW_ASYNC_UNSAFE"] = "true"

pd.set_option('display.max_rows', 500)

In [4]:
per=Person.objects.get(pk=70903810)
per

In [40]:
objs_df=pd.DataFrame(Charge.objects.filter(account__in=[13802005], value__gt=0, ledger__third_party=per).order_by('concept__date').values()).drop(['state_change_user_id', 'state_change_date', 'state', 'settled', 'id'], axis=1)
objs_df

,ledger_id,account_id,value,concept_id
0,FV-00000413,13802005,730000,Facturacion Arriendo sin IVA^2022-01-01_A6N-13...
1,FV-00000423,13802005,2600000,Facturacion Arriendo sin IVA^2022-01-01_A6N-13...
2,FV-00000414,13802005,730000,Facturacion Arriendo sin IVA^2022-02-01_A6N-13...
3,FV-00000424,13802005,2720000,Facturacion Arriendo sin IVA^2022-02-01_A6N-13...
4,FV-00000415,13802005,730000,Facturacion Arriendo sin IVA^2022-03-01_A6N-13...
5,FV-00000425,13802005,2720000,Facturacion Arriendo sin IVA^2022-03-01_A6N-13...
6,FV-00000416,13802005,790000,Facturacion Arriendo sin IVA^2022-04-01_A6N-13...
7,FV-00000426,13802005,2720000,Facturacion Arriendo sin IVA^2022-04-01_A6N-13...
8,FV-00000417,13802005,790000,Facturacion Arriendo sin IVA^2022-05-01_A6N-13...
9,FV-00000427,13802005,2720000,Facturacion Arriendo sin IVA^2022-05-01_A6N-13...
10,FV-00000418,13802005,790000,Facturacion Arriendo sin IVA^2022-06-01_A6N-13...
11,FV-00000428,13802005,2720000,Facturacion Arriendo sin IVA^2022-06-01_A6N-13...
12,FV-00000419,13802005,790000,Facturacion Arriendo sin IVA^2022-07-01_A6N-13...
13,FV-00000429,13802005,2720000,Facturacion Arriendo sin IVA^2022-07-01_A6N-13...
14,FV-00000420,13802005,790000,Facturacion Arriendo sin IVA^2022-08-01_A6N-13...
15,FV-00000430,13802005,2720000,Facturacion Arriendo sin IVA^2022-08-01_A6N-13...
16,FV-00000421,13802005,790000,Facturacion Arriendo sin IVA^2022-09-01_A6N-13...
17,FV-00000431,13802005,2720000,Facturacion Arriendo sin IVA^2022-09-01_A6N-13...
18,FV-00000422,13802005,790000,Facturacion Arriendo sin IVA^2022-10-01_A6N-13...
19,FV-00000432,13802005,2720000,Facturacion Arriendo sin IVA^2022-10-01_A6N-13...

In [41]:
receipt=-Charge.objects.filter(account__in=[13802005], value__lt=0, ledger__third_party=per).aggregate(receipt=Sum('value'))['receipt']
receipt

31270000

In [ ]:
def DueAge(_dueDate):
    bufferDate=_dueDate
    months=0
    days=0
    while bufferDate < datetime.date.today():
        if bufferDate + relativedelta(months=1) < datetime.date.today():
            months = months +1
        else:
            days=(datetime.date.today() - bufferDate).days
        bufferDate = bufferDate + relativedelta(months=1)
    return f'{months}, {days}'

In [46]:
value_sum_df=objs_df.assign(due=objs_df['value'].cumsum())
due_sum_df = value_sum_df.assign(due=value_sum_df.due.apply(lambda x: 0 if x < receipt else x - receipt))
due_df=due_sum_df.assign(due=due_sum_df.apply(lambda x: x.due if x.due < x.value else x.value, axis=1))
filtered_due_df=due_df[due_df['due'] > 0]
age_due_df=filtered_due_df.assign(age=filtered_due_df.concept_id.apply(lambda x: (datetime.date.today() - Accountable_Concept.objects.get(pk=x).date).months))
age_due_df

AttributeError: 'datetime.timedelta' object has no attribute 'months'

In [8]:
pd.DataFrame(Charge.objects.filter(account__in=[13802005], value__lt=0, ledger__third_party=per).values()).drop(['state_change_user_id', 'state_change_date', 'state'], axis=1)

,id,ledger_id,account_id,value,concept_id,settled
0,1205,RC-00000011,13802005,-800000,Ingreso Arriendo sin IVA^2022-01-18_A6N-13N-68...,False
1,1209,RC-00000012,13802005,-750000,Ingreso Arriendo sin IVA^2022-01-25_A6N-13N-68...,False
2,1213,RC-00000013,13802005,-200000,Ingreso Arriendo sin IVA^2022-01-26_A6N-13N-68...,False
3,1217,RC-00000014,13802005,-850000,Ingreso Arriendo sin IVA^2022-01-28_A6N-13N-68...,False
4,1221,RC-00000015,13802005,-700000,Ingreso Arriendo sin IVA^2022-02-14_A6N-13N-68...,False
5,1225,RC-00000016,13802005,-1500000,Ingreso Arriendo sin IVA^2022-02-22_A6N-13N-68...,False
6,1229,RC-00000017,13802005,-250000,Ingreso Arriendo sin IVA^2022-02-28_A6N-13N-68...,False
7,1233,RC-00000018,13802005,-270000,Ingreso Arriendo sin IVA^2022-03-02_A6N-13N-68...,False
8,1237,RC-00000019,13802005,-2000000,Ingreso Arriendo sin IVA^2022-03-23_A6N-13N-68...,False
9,1241,RC-00000020,13802005,-720000,Ingreso Arriendo sin IVA^2022-03-31_A6N-13N-68...,False
10,1245,RC-00000021,13802005,-2000000,Ingreso Arriendo sin IVA^2022-04-22_A6N-13N-68...,False
11,1249,RC-00000022,13802005,-720000,Ingreso Arriendo sin IVA^2022-05-05_A6N-13N-68...,False
12,1253,RC-00000023,13802005,-1800000,Ingreso Arriendo sin IVA^2022-05-23_A6N-13N-68...,False
13,1257,RC-00000024,13802005,-920000,Ingreso Arriendo sin IVA^2022-06-03_A6N-13N-68...,False
14,1261,RC-00000025,13802005,-1350000,Ingreso Arriendo sin IVA^2022-06-29_A6N-13N-68...,False
15,1265,RC-00000026,13802005,-1370000,Ingreso Arriendo sin IVA^2022-07-08_A6N-13N-68...,False
16,1269,RC-00000027,13802005,-2000000,Ingreso Arriendo sin IVA^2022-07-25_A6N-13N-68...,False
17,1273,RC-00000028,13802005,-720000,Ingreso Arriendo sin IVA^2022-08-03_A6N-13N-68...,False
18,1277,RC-00000029,13802005,-1000000,Ingreso Arriendo sin IVA^2022-08-24_A6N-13N-68...,False
19,1281,RC-00000030,13802005,-1500000,Ingreso Arriendo sin IVA^2022-08-26_A6N-13N-68...,False
20,1285,RC-00000031,13802005,-220000,Ingreso Arriendo sin IVA^2022-08-28_A6N-13N-68...,False
21,1289,RC-00000032,13802005,-1000000,Ingreso Arriendo sin IVA^2022-09-14_A6N-13N-68...,False
22,1293,RC-00000033,13802005,-1000000,Ingreso Arriendo sin IVA^2022-09-20_A6N-13N-68...,False
23,1297,RC-00000034,13802005,-200000,Ingreso Arriendo sin IVA^2022-09-20_A6N-13N-68...,False
24,1301,RC-00000035,13802005,-500000,Ingreso Arriendo sin IVA^2022-09-30_A6N-13N-68...,False
25,1305,RC-00000036,13802005,-730000,Ingreso Arriendo sin IVA^2022-01-14_A6N-13N-66...,False
26,1309,RC-00000037,13802005,-730000,Ingreso Arriendo sin IVA^2022-02-14_A6N-13N-66...,False
27,1313,RC-00000038,13802005,-730000,Ingreso Arriendo sin IVA^2022-03-11_A6N-13N-66...,False
28,1317,RC-00000039,13802005,-790000,Ingreso Arriendo sin IVA^2022-04-19_A6N-13N-66...,False
29,1321,RC-00000040,13802005,-790000,Ingreso Arriendo sin IVA^2022-05-23_A6N-13N-66...,False
30,1325,RC-00000041,13802005,-790000,Ingreso Arriendo sin IVA^2022-06-14_A6N-13N-66...,False
31,1329,RC-00000042,13802005,-790000,Ingreso Arriendo sin IVA^2022-07-15_A6N-13N-66...,False
32,1333,RC-00000043,13802005,-700000,Ingreso Arriendo sin IVA^2022-08-09_A6N-13N-66...,False
33,1337,RC-00000044,13802005,-90000,Ingreso Arriendo sin IVA^2022-08-16_A6N-13N-66...,False
34,1341,RC-00000045,13802005,-790000,Ingreso Arriendo sin IVA^2022-09-14_A6N-13N-66...,False

3530000